[package]
name = "selog"
version = "0.1.0"
description = "Simple, Easy LOGger logs to StdErr."
authors = ["watcol <kantaa058@gmail.com>"]
homepage = "https://github.com/watcol/selog"
repository = "https://github.com/watcol/selog"
keywards = ["log", "logger", "loglevel"]
categories = ["development-tools::debugging"]
license = "MIT"
readme = "README.md"
edition = "2018"

include = [
  "README.md",
  "Cargo.toml",
  "src/**/*.rs"
]

[dependencies]
ansi_term = "0.12"
atty = "0.2"

[dependencies.log]
version = "0.4"
features = ["std"]
